### PR TITLE
Recipe App - Application Ready to be Released

### PR DESCRIPTION
**Pull request by rpire**
# Implemented Features
## Database
- Database was created from the given **Entity Relationship Diagram (ERD)**.
- All table relationships were implemented according to what was given in the **ERD**
- See the provided **ERD** [here](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/images/recipe_app_erd.png).
## Models
- Validations were added to each model.
- Authorizations were implemented using the `cancancan` gem and implementing an `Ability` class.
- Relationships between entities were enforced in the models using the `belongs_to` and `has_many` methods.
- Unit tests were written for each model using the `rspec-rails` gem.
## Views
- All views follow the layout of the provided wireframes.
- Login page:
  - Login page was built using the `devise` gem.
- Food list:
  - A list of food was displayed in this view as in the provided [wireframe](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/images/food_index.png).
- Recipes list:
  - A list of recipes created by the logged-in user was displayed in this view as in the provided [wireframe](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/images/recipe_index.png).
- Public recipe list:
  - A list of all public recipes ordered by newest was displayed here as in the [wireframe](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/images/public_recipe_index.png).
- Recipe details:
  - Details about the recipes were displayed in this view if it is public or if the user is the owner of the recipe.
  - Users can add ingredients to the recipe if they are the owner of it.
  - The provided [wireframe](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/images/recipe_food_shopping_list.png) was followed for this page's view.
- General shopping list:
  - A list of ingredients with their quantity and price was displayed in this view as in the provided [wireframe](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/images/inventory_shopping_list.png).
  - Total food items and total price for the shopping lists are displayed.
- Integrations tests were added to each view using the `rspec-rails` and `capybara` gems.
## Controllers
- Controllers were added to implement **CRUD** operations on each view.
## Additionally
- All **N + 1 query** problems were solved.
- A navigation menu was created to open the created pages.

### CODE REVIEW

**Review by AshakaE — CHANGES_REQUESTED** [review]
### Hi @rpire & @ReshyResh  🙋‍♀️, 

Good job so far! 👌
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights ⚡ 

- Your: 
    - Test cases pass ✔️ 
    - README 👍 
    - Git flow ✔️ 
    - Pull request ✔️  


#  Required Changes ♻️ 🚧
_Check the comments under the review._

 Your application works but I'm unable to access the pages because I need email confirmation

- [ ] Please fix the user login 🙂 

###  Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rpire** [comment]
Hello, @AshakaE 👋

Once you sign up, you can see the email confirmation URL in the console in which you are running the server for the rails application. I thought that code reviewers knew this and didn't I care too much about explaining it in the `README.md` file.

We will remove the email confirmation since it wasn't even a requirement for this project and request another review. 😅

Thanks for reviewing our work, cheers! 🤓

**Review by DeliceLydia — APPROVED** [review]
# Congratulations🎉🎉

## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Keep Rocking!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard).. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rpire** [comment]
Hello, @DeliceLydia 🙌

Thank you for reviewing our work. We will proceed to merge this PR and submit our project. 🚀

Thank you again for reviewing our project. Cheers and Happy coding to you too! 🤓

**Pull request merged**
